/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_v1_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Measurements */
        get: operations["list_measurements_api_v1_devices__device_id__measurements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explore */
        get: operations["explore_api_v1_explore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/ttn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Ttn Webhook */
        post: operations["receive_ttn_webhook_api_v1_ingestion_ttn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sites */
        get: operations["list_sites_api_v1_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site */
        get: operations["get_site_api_v1_sites__site_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConnectivityStatus
         * @enum {string}
         */
        ConnectivityStatus: "unknown" | "online" | "stale" | "offline";
        /** DeviceDetail */
        DeviceDetail: {
            /** Channels */
            channels: components["schemas"]["SensorChannelPublic"][];
            /** Device Type */
            device_type: string;
            /** Display Name */
            display_name: string;
            freshness: components["schemas"]["Freshness"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Seen At */
            last_seen_at: string | null;
            latest_battery: components["schemas"]["MeasurementValue"] | null;
            /** Latest Measurements */
            latest_measurements: components["schemas"]["MeasurementValue"][];
            /** Location Disclosure */
            location_disclosure: string;
            monitoring_feature: components["schemas"]["MonitoringFeaturePublic"] | null;
            /** Operational Override */
            operational_override: string | null;
            /** Sensor Configuration Status */
            sensor_configuration_status: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Site Name */
            site_name: string;
        };
        /** DeviceList */
        DeviceList: {
            /** Items */
            items: components["schemas"]["DevicePublic"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Reference Time
             * Format: date-time
             */
            reference_time: string;
            /** Synthetic */
            synthetic: boolean;
        };
        /** DevicePublic */
        DevicePublic: {
            /** Device Type */
            device_type: string;
            /** Display Name */
            display_name: string;
            freshness: components["schemas"]["Freshness"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Seen At */
            last_seen_at: string | null;
            latest_battery: components["schemas"]["MeasurementValue"] | null;
            /** Location Disclosure */
            location_disclosure: string;
            monitoring_feature: components["schemas"]["MonitoringFeaturePublic"] | null;
            /** Operational Override */
            operational_override: string | null;
            /** Sensor Configuration Status */
            sensor_configuration_status: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Site Name */
            site_name: string;
        };
        /** DeviceStatusCounts */
        DeviceStatusCounts: {
            /** Offline */
            offline: number;
            /** Online */
            online: number;
            /** Stale */
            stale: number;
            /** Total */
            total: number;
            /** Unknown */
            unknown: number;
        };
        /** ExploreChannel */
        ExploreChannel: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Channel Name */
            channel_name: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Device Name */
            device_name: string;
            /** Expected Reporting Interval Seconds */
            expected_reporting_interval_seconds: number | null;
            /**
             * Feature Id
             * Format: uuid
             */
            feature_id: string;
            /** Feature Name */
            feature_name: string;
            /** Feature Slug */
            feature_slug: string;
            /** Installation Depth Cm */
            installation_depth_cm: number | null;
            /** Metric Code */
            metric_code: string;
            /** Metric Group */
            metric_group: string;
            /** Metric Name */
            metric_name: string;
            /** Position Label */
            position_label: string | null;
            /** Reporting Jitter Tolerance Seconds */
            reporting_jitter_tolerance_seconds: number | null;
            /** Reporting Schedule Anchor At */
            reporting_schedule_anchor_at: string | null;
            /** Unit Code */
            unit_code: string | null;
            /** Unit Confirmation Status */
            unit_confirmation_status: string;
            /** Unit Symbol */
            unit_symbol: string | null;
            /** Water Level Reference Or Datum */
            water_level_reference_or_datum: string | null;
        };
        /** ExploreCoverage */
        ExploreCoverage: {
            /** Coverage Percentage */
            coverage_percentage: number | null;
            /** Duplicate Slot Observations */
            duplicate_slot_observations: number;
            /** Expected Observations */
            expected_observations: number | null;
            /** Flagged Observations */
            flagged_observations: number | null;
            /** Late Observations */
            late_observations: number;
            /** Missing Intervals */
            missing_intervals: components["schemas"]["ExploreMissingInterval"][];
            /** Missing Observations */
            missing_observations: number | null;
            /** Out Of Tolerance Observations */
            out_of_tolerance_observations: number;
            /** Received Observations */
            received_observations: number | null;
            /** Status */
            status: string;
            /** Status Detail */
            status_detail: string;
            /** Valid Observations */
            valid_observations: number | null;
        };
        /** ExploreDevice */
        ExploreDevice: {
            current_freshness: components["schemas"]["Freshness"];
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Device Name */
            device_name: string;
            /** Device Type */
            device_type: string;
            /**
             * Feature Id
             * Format: uuid
             */
            feature_id: string;
            /** Feature Name */
            feature_name: string;
            /** Feature Slug */
            feature_slug: string;
            /** Sensor Configuration Status */
            sensor_configuration_status: string;
        };
        /** ExploreMissingInterval */
        ExploreMissingInterval: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Expected Slots */
            expected_slots: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** ExplorePoint */
        ExplorePoint: {
            /** Expected Slot At */
            expected_slot_at: string | null;
            /** Included In Summary */
            included_in_summary: boolean;
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            /**
             * Measurement Id
             * Format: uuid
             */
            measurement_id: string;
            /** Numeric Value */
            numeric_value: number;
            /** Quality Flag */
            quality_flag: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Timing Status */
            timing_status: string;
            /** Transmission Delay Seconds */
            transmission_delay_seconds: number;
        };
        /** ExploreResponse */
        ExploreResponse: {
            /** Available Channels */
            available_channels: components["schemas"]["ExploreChannel"][];
            /** Available Devices */
            available_devices: components["schemas"]["ExploreDevice"][];
            /** Display Timezone */
            display_timezone: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Feature */
            feature: string | null;
            /** Metric Group */
            metric_group: string;
            /** Quality Warnings */
            quality_warnings: components["schemas"]["QualityWarning"][];
            /**
             * Reference Time
             * Format: date-time
             */
            reference_time: string;
            /** Selected Channel Ids */
            selected_channel_ids: string[];
            /** Series */
            series: components["schemas"]["ExploreSeries"][];
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Site Name */
            site_name: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Synthetic */
            synthetic: boolean;
            /** Time Window Semantics */
            time_window_semantics: string;
        };
        /** ExploreSeries */
        ExploreSeries: {
            channel: components["schemas"]["ExploreChannel"];
            coverage: components["schemas"]["ExploreCoverage"];
            /** Points */
            points: components["schemas"]["ExplorePoint"][];
            summary: components["schemas"]["ExploreSummary"];
        };
        /** ExploreSummary */
        ExploreSummary: {
            /** Statistics */
            statistics: components["schemas"]["ExploreSummaryStatistic"][];
            /** Status */
            status: string;
            /** Status Detail */
            status_detail: string;
        };
        /** ExploreSummaryStatistic */
        ExploreSummaryStatistic: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Observed At */
            observed_at: string | null;
            /** Value */
            value: number;
        };
        /** Freshness */
        Freshness: {
            /** Age Seconds */
            age_seconds: number | null;
            calculated_status: components["schemas"]["ConnectivityStatus"];
            /** Offline After Minutes */
            offline_after_minutes: number;
            /**
             * Reference Time
             * Format: date-time
             */
            reference_time: string;
            /** Stale After Minutes */
            stale_after_minutes: number;
            /** Status Basis */
            status_basis: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Database */
            database: string;
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Version */
            version: string;
        };
        /** MeasurementPage */
        MeasurementPage: {
            /** Default Range Applied */
            default_range_applied: boolean;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Items */
            items: components["schemas"]["MeasurementValue"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Reference Time
             * Format: date-time
             */
            reference_time: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Synthetic */
            synthetic: boolean;
            /** Total Matching */
            total_matching: number;
        };
        /** MeasurementValue */
        MeasurementValue: {
            /** Channel Code */
            channel_code: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Channel Name */
            channel_name: string;
            /** Depth Cm */
            depth_cm: number | null;
            /** Installation Depth Cm */
            installation_depth_cm: number | null;
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            /** Metric Code */
            metric_code: string;
            /** Metric Name */
            metric_name: string;
            /** Numeric Value */
            numeric_value: number;
            /** Position Label */
            position_label: string | null;
            /** Quality Flag */
            quality_flag: string;
            /** Quality Notes */
            quality_notes: string | null;
            /** Unit Code */
            unit_code: string | null;
            /** Unit Confirmation Status */
            unit_confirmation_status: string;
            /** Unit Symbol */
            unit_symbol: string | null;
        };
        /**
         * MetricGroup
         * @enum {string}
         */
        MetricGroup: "hydrology" | "soil" | "weather" | "operational";
        /** MonitoringFeaturePublic */
        MonitoringFeaturePublic: {
            /** Display Name */
            display_name: string;
            /** Feature Type */
            feature_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Public Slug */
            public_slug: string;
        };
        /** Overview */
        Overview: {
            data_quality: components["schemas"]["QualityWindow"];
            devices: components["schemas"]["DeviceStatusCounts"];
            /** Display Timezone */
            display_timezone: string;
            /** Last Data Update */
            last_data_update: string | null;
            latest_rainfall_intensity: components["schemas"]["MeasurementValue"] | null;
            /** Public Location Label */
            public_location_label: string;
            /**
             * Reference Time
             * Format: date-time
             */
            reference_time: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Site Name */
            site_name: string;
            soil_moisture: components["schemas"]["SoilMoistureSummary"] | null;
            /** Synthetic */
            synthetic: boolean;
            /** Synthetic Notice */
            synthetic_notice: string | null;
        };
        /** QualityWarning */
        QualityWarning: {
            /** Channel Name */
            channel_name: string;
            /** Device Name */
            device_name: string;
            /** Excluded From Summaries */
            excluded_from_summaries: boolean;
            /** Explanation */
            explanation: string;
            /**
             * Measurement Id
             * Format: uuid
             */
            measurement_id: string;
            /**
             * Observation Time
             * Format: date-time
             */
            observation_time: string;
            /** Quality Flag */
            quality_flag: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
        };
        /** QualityWindow */
        QualityWindow: {
            /** End */
            end: string | null;
            /** Start */
            start: string | null;
            /** Warning Count */
            warning_count: number;
        };
        /** SensorChannelPublic */
        SensorChannelPublic: {
            /** Active */
            active: boolean;
            /** Channel Code */
            channel_code: string;
            /** Depth Cm */
            depth_cm: number | null;
            /** Display Name */
            display_name: string;
            /** Expected Reporting Interval Seconds */
            expected_reporting_interval_seconds: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Installation Depth Cm */
            installation_depth_cm: number | null;
            /** Metric Code */
            metric_code: string;
            /** Metric Name */
            metric_name: string;
            /** Position Label */
            position_label: string | null;
            /** Reporting Jitter Tolerance Seconds */
            reporting_jitter_tolerance_seconds: number | null;
            /** Reporting Schedule Anchor At */
            reporting_schedule_anchor_at: string | null;
            /** Unit Code */
            unit_code: string | null;
            /** Unit Confirmation Status */
            unit_confirmation_status: string;
            /** Unit Symbol */
            unit_symbol: string | null;
            /** Water Level Reference Or Datum */
            water_level_reference_or_datum: string | null;
        };
        /** SiteList */
        SiteList: {
            /** Items */
            items: components["schemas"]["SitePublic"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SitePublic */
        SitePublic: {
            /** Active */
            active: boolean;
            /** Description */
            description: string | null;
            /** Display Timezone */
            display_timezone: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location Disclosure */
            location_disclosure: string;
            /** Name */
            name: string;
            /** Public Location Label */
            public_location_label: string;
        };
        /** SoilChannelObservation */
        SoilChannelObservation: {
            /** Channel Code */
            channel_code: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Channel Name */
            channel_name: string;
            /** Depth Cm */
            depth_cm: number | null;
            /** Installation Depth Cm */
            installation_depth_cm: number | null;
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            /** Metric Code */
            metric_code: string;
            /** Metric Name */
            metric_name: string;
            /** Numeric Value */
            numeric_value: number;
            /** Position Label */
            position_label: string | null;
            /** Quality Flag */
            quality_flag: string;
            /** Quality Notes */
            quality_notes: string | null;
            /** Unit Code */
            unit_code: string | null;
            /** Unit Confirmation Status */
            unit_confirmation_status: string;
            /** Unit Symbol */
            unit_symbol: string | null;
        };
        /** SoilMoistureSummary */
        SoilMoistureSummary: {
            /** Comparability Note */
            comparability_note: string;
            /** Contributing Channel Count */
            contributing_channel_count: number;
            /** Contributing Channels */
            contributing_channels: components["schemas"]["SoilChannelObservation"][];
            /** Maximum */
            maximum: number;
            /** Median */
            median: number;
            /** Metric Code */
            metric_code: string;
            /** Minimum */
            minimum: number;
            /**
             * Timestamp End
             * Format: date-time
             */
            timestamp_end: string;
            /**
             * Timestamp Start
             * Format: date-time
             */
            timestamp_start: string;
            /** Unit Code */
            unit_code: string | null;
            /** Unit Confirmation Status */
            unit_confirmation_status: string;
            /** Unit Symbol */
            unit_symbol: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: {
                search?: string | null;
                site_id?: string | null;
                feature?: string | null;
                device_type?: string | null;
                status?: components["schemas"]["ConnectivityStatus"] | null;
                page_size?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_v1_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_measurements_api_v1_devices__device_id__measurements_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                metric_code?: string | null;
                sensor_channel_id?: string | null;
                page_size?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_api_v1_explore_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                site_id?: string | null;
                feature?: string | null;
                metric_group?: components["schemas"]["MetricGroup"];
                channels?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    receive_ttn_webhook_api_v1_ingestion_ttn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query?: {
                site_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_api_v1_sites_get: {
        parameters: {
            query?: {
                page_size?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_api_v1_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
