/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_v1_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Measurements */
        get: operations["list_measurements_api_v1_devices__device_id__measurements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion/ttn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Ttn Webhook */
        post: operations["receive_ttn_webhook_api_v1_ingestion_ttn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sites */
        get: operations["list_sites_api_v1_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site */
        get: operations["get_site_api_v1_sites__site_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConnectivityStatus
         * @enum {string}
         */
        ConnectivityStatus: "unknown" | "online" | "stale" | "offline";
        /** DeviceDetail */
        DeviceDetail: {
            /** Channels */
            channels: components["schemas"]["SensorChannelPublic"][];
            /** Device Type */
            device_type: string;
            /** Display Name */
            display_name: string;
            freshness: components["schemas"]["Freshness"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Seen At */
            last_seen_at: string | null;
            latest_battery: components["schemas"]["MeasurementValue"] | null;
            /** Latest Measurements */
            latest_measurements: components["schemas"]["MeasurementValue"][];
            /** Location Disclosure */
            location_disclosure: string;
            /** Operational Override */
            operational_override: string | null;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Site Name */
            site_name: string;
        };
        /** DeviceList */
        DeviceList: {
            /** Items */
            items: components["schemas"]["DevicePublic"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Reference Time
             * Format: date-time
             */
            reference_time: string;
            /** Synthetic */
            synthetic: boolean;
        };
        /** DevicePublic */
        DevicePublic: {
            /** Device Type */
            device_type: string;
            /** Display Name */
            display_name: string;
            freshness: components["schemas"]["Freshness"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Seen At */
            last_seen_at: string | null;
            latest_battery: components["schemas"]["MeasurementValue"] | null;
            /** Location Disclosure */
            location_disclosure: string;
            /** Operational Override */
            operational_override: string | null;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Site Name */
            site_name: string;
        };
        /** DeviceStatusCounts */
        DeviceStatusCounts: {
            /** Offline */
            offline: number;
            /** Online */
            online: number;
            /** Stale */
            stale: number;
            /** Total */
            total: number;
            /** Unknown */
            unknown: number;
        };
        /** Freshness */
        Freshness: {
            /** Age Seconds */
            age_seconds: number | null;
            calculated_status: components["schemas"]["ConnectivityStatus"];
            /** Offline After Minutes */
            offline_after_minutes: number;
            /**
             * Reference Time
             * Format: date-time
             */
            reference_time: string;
            /** Stale After Minutes */
            stale_after_minutes: number;
            /** Status Basis */
            status_basis: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Database */
            database: string;
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Version */
            version: string;
        };
        /** MeasurementPage */
        MeasurementPage: {
            /** Default Range Applied */
            default_range_applied: boolean;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Items */
            items: components["schemas"]["MeasurementValue"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Reference Time
             * Format: date-time
             */
            reference_time: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Synthetic */
            synthetic: boolean;
            /** Total Matching */
            total_matching: number;
        };
        /** MeasurementValue */
        MeasurementValue: {
            /** Channel Code */
            channel_code: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Channel Name */
            channel_name: string;
            /** Depth Cm */
            depth_cm: number | null;
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            /** Metric Code */
            metric_code: string;
            /** Metric Name */
            metric_name: string;
            /** Numeric Value */
            numeric_value: number;
            /** Position Label */
            position_label: string | null;
            /** Quality Flag */
            quality_flag: string;
            /** Quality Notes */
            quality_notes: string | null;
            /** Unit Code */
            unit_code: string;
            /** Unit Symbol */
            unit_symbol: string;
        };
        /** Overview */
        Overview: {
            data_quality: components["schemas"]["QualityWindow"];
            devices: components["schemas"]["DeviceStatusCounts"];
            /** Display Timezone */
            display_timezone: string;
            /** Last Data Update */
            last_data_update: string | null;
            latest_rainfall: components["schemas"]["MeasurementValue"] | null;
            /** Public Location Label */
            public_location_label: string;
            /**
             * Reference Time
             * Format: date-time
             */
            reference_time: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Site Name */
            site_name: string;
            soil_moisture: components["schemas"]["SoilMoistureSummary"] | null;
            /** Synthetic */
            synthetic: boolean;
            /** Synthetic Notice */
            synthetic_notice: string | null;
        };
        /** QualityWindow */
        QualityWindow: {
            /** End */
            end: string | null;
            /** Start */
            start: string | null;
            /** Warning Count */
            warning_count: number;
        };
        /** SensorChannelPublic */
        SensorChannelPublic: {
            /** Active */
            active: boolean;
            /** Channel Code */
            channel_code: string;
            /** Depth Cm */
            depth_cm: number | null;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metric Code */
            metric_code: string;
            /** Metric Name */
            metric_name: string;
            /** Position Label */
            position_label: string | null;
            /** Unit Code */
            unit_code: string;
            /** Unit Symbol */
            unit_symbol: string;
        };
        /** SiteList */
        SiteList: {
            /** Items */
            items: components["schemas"]["SitePublic"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SitePublic */
        SitePublic: {
            /** Active */
            active: boolean;
            /** Description */
            description: string | null;
            /** Display Timezone */
            display_timezone: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location Disclosure */
            location_disclosure: string;
            /** Name */
            name: string;
            /** Public Location Label */
            public_location_label: string;
        };
        /** SoilChannelObservation */
        SoilChannelObservation: {
            /** Channel Code */
            channel_code: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Channel Name */
            channel_name: string;
            /** Depth Cm */
            depth_cm: number | null;
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            /** Metric Code */
            metric_code: string;
            /** Metric Name */
            metric_name: string;
            /** Numeric Value */
            numeric_value: number;
            /** Position Label */
            position_label: string | null;
            /** Quality Flag */
            quality_flag: string;
            /** Quality Notes */
            quality_notes: string | null;
            /** Unit Code */
            unit_code: string;
            /** Unit Symbol */
            unit_symbol: string;
        };
        /** SoilMoistureSummary */
        SoilMoistureSummary: {
            /** Comparability Note */
            comparability_note: string;
            /** Contributing Channel Count */
            contributing_channel_count: number;
            /** Contributing Channels */
            contributing_channels: components["schemas"]["SoilChannelObservation"][];
            /** Maximum */
            maximum: number;
            /** Median */
            median: number;
            /** Metric Code */
            metric_code: string;
            /** Minimum */
            minimum: number;
            /**
             * Timestamp End
             * Format: date-time
             */
            timestamp_end: string;
            /**
             * Timestamp Start
             * Format: date-time
             */
            timestamp_start: string;
            /** Unit Code */
            unit_code: string;
            /** Unit Symbol */
            unit_symbol: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: {
                search?: string | null;
                site_id?: string | null;
                device_type?: string | null;
                status?: components["schemas"]["ConnectivityStatus"] | null;
                page_size?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_v1_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_measurements_api_v1_devices__device_id__measurements_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                metric_code?: string | null;
                sensor_channel_id?: string | null;
                page_size?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    receive_ttn_webhook_api_v1_ingestion_ttn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query?: {
                site_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_api_v1_sites_get: {
        parameters: {
            query?: {
                page_size?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_api_v1_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
